import { strict as assert } from "node:assert";
import { spawn } from "node:child_process";
import fs from "node:fs";
import http from "node:http";
import os from "node:os";
import path from "node:path";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";
import {
	GENERATED_MARKER,
	hasLegacyCustomModelOption,
	isOurRow,
	noticeFor,
	pickerNotice,
	pickerNoticeState,
	readPickerRows,
	readStamp,
	writeStamp,
} from "../hooks/picker-staleness.js";

// Issue #62. The generated modelPicker rows are a SNAPSHOT: CONTEXT_WINDOW
// changing under them (a corrected window, an id crossing 1M and gaining its
// [1m] suffix) makes them wrong with no symptom — the picker still renders, the
// stale window is still enforced, nothing errors. This notice is the only thing
// that would ever tell the user, so its gating is the whole test surface.

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const tmp = () => fs.mkdtempSync(path.join(os.tmpdir(), "cc-stale-"));

// A row as buildRows() actually emits it. The description marker is what makes
// it OURS — a bare { model } is indistinguishable from a row the user wrote by
// hand, and treating those as ours told people with their own picker to re-run
// a setup they never ran.
const OUR_ROW = {
	model: "glm-5.3[1m]",
	label: "GLM-5.3 (1M)",
	description: `1M context, ${GENERATED_MARKER}`,
	behavesAs: "claude-sonnet-5",
};
const FOREIGN_ROW = { model: "my-gateway/claude-opus-5", label: "Work gateway" };

describe("picker staleness gating (issue #62)", () => {
	// Silence is the default and the common case: a healthy line every session
	// is noise the context pays for forever.
	it("says nothing when the stamp matches this version", () => {
		assert.equal(
			pickerNoticeState({
				version: "0.9.2",
				notified: "0.9.2",
				rows: [OUR_ROW],
				legacyEnv: false,
			}),
			null,
		);
	});

	it("reports stale rows after a version change", () => {
		assert.equal(
			pickerNoticeState({
				version: "0.10.0",
				notified: "0.9.2",
				rows: [OUR_ROW],
				legacyEnv: false,
			}),
			"stale",
		);
	});

	// The pre-#62 configuration: one model in the picker, and CC's 200K
	// assumption on every other id cc-proxy routes.
	it("reports the legacy one-slot config when there are no rows", () => {
		assert.equal(
			pickerNoticeState({
				version: "0.10.0",
				notified: undefined,
				rows: undefined,
				legacyEnv: true,
			}),
			"absent",
		);
		assert.equal(
			pickerNoticeState({ version: "0.10.0", notified: undefined, rows: [], legacyEnv: true }),
			"absent",
		);
	});

	// A user with no rows AND no legacy env never opted into any of this.
	// Volunteering config advice to someone who never asked is how a hook becomes
	// noise; this is the case that keeps the notice from firing for everyone.
	it("stays silent for a user who never configured a picker at all", () => {
		assert.equal(
			pickerNoticeState({
				version: "0.10.0",
				notified: undefined,
				rows: undefined,
				legacyEnv: false,
			}),
			null,
		);
	});

	// THE ROW-OWNERSHIP GATE, both directions. Counting any modelPicker row as
	// ours told a user who curates their own picker that OUR rows were stale —
	// advice to re-run a setup they never ran — and, worse, let their rows
	// suppress the "absent" notice that was actually for them. Whether cc-proxy
	// has anything to say depends on cc-proxy's own rows, never on the picker
	// being non-empty.
	it("ignores rows it did not generate", () => {
		assert.equal(
			pickerNoticeState({
				version: "0.10.0",
				notified: "0.9.2",
				rows: [FOREIGN_ROW, { model: "some-other/model" }],
				legacyEnv: false,
			}),
			null,
			"a user's own picker rows were reported as cc-proxy rows gone stale",
		);
		assert.equal(
			pickerNoticeState({
				version: "0.10.0",
				notified: undefined,
				rows: [FOREIGN_ROW],
				legacyEnv: true,
			}),
			"absent",
			"a foreign row suppressed the legacy-config notice, which is the one that was for them",
		);
		// And ours are still found when they sit among foreign ones.
		assert.equal(
			pickerNoticeState({
				version: "0.10.0",
				notified: "0.9.2",
				rows: [FOREIGN_ROW, OUR_ROW],
				legacyEnv: false,
			}),
			"stale",
		);
	});

	it("recognizes a generated row by its description marker", () => {
		assert.equal(isOurRow(OUR_ROW), true);
		assert.equal(isOurRow(FOREIGN_ROW), false);
		// A bare model id is NOT enough: the user may have written it themselves,
		// and the whole point of the marker is that we cannot tell otherwise.
		assert.equal(isOurRow({ model: "glm-5.3[1m]" }), false);
		assert.equal(isOurRow(null), false);
		assert.equal(isOurRow({ description: 5 }), false);
	});

	// A DOWNGRADE notifies too, and that is deliberate: the gate is "the rows
	// were generated by a different version", not "an older one". Rolling back
	// the plugin (a release revert, a git checkout during dev) leaves rows the
	// running tree may not agree with — an id the new-old version does not curate
	// still sits in the picker, budgeted against a window this tree never
	// published. Pinned because a semver-aware "only on upgrade" rewrite looks
	// like a refinement and would pass the whole suite without this.
	it("notifies on a downgrade as well as an upgrade", () => {
		assert.equal(
			pickerNoticeState({
				version: "0.9.9",
				notified: "0.10.0",
				rows: [OUR_ROW],
				legacyEnv: false,
			}),
			"stale",
		);
	});

	// An unreadable package.json must not mean "notify on every session forever".
	it("stays silent when this tree's version is unknown", () => {
		assert.equal(
			pickerNoticeState({ version: undefined, notified: undefined, rows: [], legacyEnv: true }),
			null,
		);
	});

	it("names the fix in both notices", () => {
		for (const state of /** @type {const} */ (["absent", "stale"])) {
			const line = noticeFor(state, "0.9.2");
			assert.match(line, /cc-proxy:setup|render-model-picker/);
			assert.match(line, /^cc-proxy 0\.9\.2:/);
		}
		// The "absent" line must say WHY it matters, or it reads as a nag.
		assert.match(noticeFor("absent", "0.9.2"), /200K/);
	});
});

describe("picker staleness I/O (issue #62)", () => {
	it("fires once per version, then goes quiet", () => {
		const dir = tmp();
		const settings = path.join(dir, "settings.json");
		const stamp = path.join(dir, "stamp.json");
		fs.writeFileSync(settings, JSON.stringify({ modelPicker: { options: [OUR_ROW] } }));

		const first = pickerNotice({ version: "0.9.9", settingsFile: settings, stampFile: stamp });
		assert.match(first, /modelPicker rows/);
		const second = pickerNotice({ version: "0.9.9", settingsFile: settings, stampFile: stamp });
		assert.equal(second, undefined, "the notice repeated within one version");
		const afterUpdate = pickerNotice({
			version: "0.10.0",
			settingsFile: settings,
			stampFile: stamp,
		});
		assert.match(afterUpdate, /modelPicker rows/, "the notice did not return after an update");
	});

	// The "absent" case is the one a user may deliberately decline. Stamping it
	// too is what stops it becoming a permanent every-session line.
	it("stamps the legacy-config notice too", () => {
		const dir = tmp();
		const settings = path.join(dir, "settings.json");
		const stamp = path.join(dir, "stamp.json");
		fs.writeFileSync(
			settings,
			JSON.stringify({ env: { ANTHROPIC_CUSTOM_MODEL_OPTION: "glm-5.3[1m]" } }),
		);
		assert.match(
			pickerNotice({ version: "0.9.9", settingsFile: settings, stampFile: stamp }),
			/200K/,
		);
		assert.equal(
			pickerNotice({ version: "0.9.9", settingsFile: settings, stampFile: stamp }),
			undefined,
		);
	});

	// Every reader here runs inside a SessionStart hook: a throw is a session
	// that starts without its proxy notice, or at all.
	it("survives every unreadable input", () => {
		const dir = tmp();
		assert.equal(readStamp(path.join(dir, "nope.json")), undefined);
		assert.equal(readPickerRows(path.join(dir, "nope.json")), undefined);
		assert.equal(hasLegacyCustomModelOption(path.join(dir, "nope.json")), false);
		const junk = path.join(dir, "junk.json");
		fs.writeFileSync(junk, "{ not json");
		assert.equal(readStamp(junk), undefined);
		assert.equal(readPickerRows(junk), undefined);
		assert.equal(hasLegacyCustomModelOption(junk), false);
		// A picker whose options is not an array reads as "no rows", not a throw.
		const odd = path.join(dir, "odd.json");
		fs.writeFileSync(odd, JSON.stringify({ modelPicker: { options: "glm" } }));
		assert.equal(readPickerRows(odd), undefined);
		// An unwritable stamp path must not throw either.
		//
		// The unwritable path is made by putting a FILE where a directory has to
		// go, which is ENOTDIR on every platform. The first version used
		// "/proc/nope/stamp.json", which is only reliably unwritable on macOS,
		// where /proc does not exist and mkdirSync fails instantly with ENOENT. On
		// Linux /proc is a live kernel filesystem, so that same call does
		// something else entirely — and this file then timed out on CI at 60s
		// having reported NO subtest, since the failure happens while the suite is
		// still being constructed. A path that behaves differently per platform is
		// not a test of "unwritable"; it is a test of the developer's OS.
		const blocked = path.join(dir, "blocked");
		fs.writeFileSync(blocked, "not a directory");
		assert.doesNotThrow(() => writeStamp("0.9.9", path.join(blocked, "stamp.json")));
	});

	// Same rule as settings.json, lower stakes: a torn stamp reads as "never
	// notified" and costs one extra notice. Uniform anyway — the next person to
	// copy a writer out of this tree should copy a correct one. INODE, because a
	// truncating write reuses it and a rename installs the temp file's; "no .tmp
	// survives" passes against both.
	it("writes the stamp by rename, not in place", () => {
		const dir = tmp();
		const file = path.join(dir, "stamp.json");
		writeStamp("0.9.0", file);
		const before = fs.statSync(file).ino;
		writeStamp("0.10.0", file);
		assert.notEqual(fs.statSync(file).ino, before, "the stamp was truncated in place");
		assert.equal(readStamp(file), "0.10.0");
		assert.deepEqual(
			fs.readdirSync(dir).filter((f) => f.includes(".tmp-")),
			[],
			"a temp file survived a successful stamp write",
		);
	});
});

describe("session-start emits one payload (issue #62)", () => {
	/**
	 * A plugin tree holding ONLY the three hook files and a package.json —
	 * deliberately NO `bin/`.
	 *
	 * THIS IS A SAFETY PROPERTY, NOT A CONVENIENCE. `resolveProxyPath()` prefers
	 * the tree's own `bin/cc-proxy.js` and only falls back to env `PROXY_PATH`,
	 * so running the REPO's hook from a test means any code path that decides to
	 * spawn starts a REAL, DETACHED, unref'd proxy on the runner. That is
	 * unkillable by the test and it does not merely leak: a CI step never
	 * finishes while an orphaned child of it is alive, so the job hangs with no
	 * log and no failing test name (measured — 6+ minutes in `pnpm test` against
	 * ~10 s locally, twice, before `--test-timeout` turned it into a nameable
	 * failure). With no `bin/` and `PROXY_PATH=""` the spawn is unreachable by
	 * construction rather than by argument.
	 *
	 * The package.json is load-bearing too: both hooks read their own tree's
	 * version, and without one `treeVersion()` is undefined, `pickerNoticeState`
	 * returns null, and a test asserting the picker line would pass while
	 * measuring only the proxy line.
	 *
	 * @param {string} dir  the fake HOME
	 * @returns {string} path to the tree's session-start.js
	 */
	function isolatedHook(dir) {
		const hooks = path.join(dir, "tree", "hooks");
		fs.mkdirSync(hooks, { recursive: true });
		for (const f of ["session-start.js", "proxy-lifecycle.js", "picker-staleness.js"]) {
			fs.copyFileSync(path.join(root, "hooks", f), path.join(hooks, f));
		}
		fs.writeFileSync(
			path.join(dir, "tree", "package.json"),
			JSON.stringify({ name: "cc-proxy", version: "0.9.9", type: "module" }),
		);
		return path.join(hooks, "session-start.js");
	}

	/**
	 * Run the isolated hook and resolve its stdout.
	 *
	 * `spawn` + resolve on `exit`, which is the shape proxy-lifecycle.test.js
	 * already uses for this hook and is proven on CI. Two earlier spellings were
	 * not:
	 *
	 * - `execFileSync` BLOCKS this process's event loop, so an in-process
	 *   /_status server cannot answer while the hook runs. The "already-up" test
	 *   then passed only because that 1 s probe expired inside the exec — a pass
	 *   for the wrong reason, decided by a margin that shifts under CI load.
	 * - `execFile` resolves when the child's STDIO CLOSES, not when it exits, so
	 *   anything still holding the pipe keeps the promise pending forever. On the
	 *   runner the whole FILE timed out at 60 s having reported no subtest at all
	 *   — the least actionable failure shape there is.
	 *
	 * `exit` fires when the process ends regardless of who else holds a
	 * descriptor, and stderr goes to the parent so a crash in the child is
	 * visible rather than swallowed.
	 *
	 * @param {string} dir @param {Record<string,string>} env
	 * @returns {Promise<string>}
	 */
	function runHook(dir, env) {
		const child = spawn(process.execPath, [isolatedHook(dir)], {
			env: {
				...process.env,
				HOME: dir,
				USERPROFILE: dir,
				PROXY_PATH: "",
				PROXY_READY_TIMEOUT_MS: "300",
				PROXY_LOG: path.join(dir, "log"),
				...env,
			},
			stdio: ["ignore", "pipe", "inherit"],
		});
		return new Promise((resolve, reject) => {
			let out = "";
			child.stdout.on("data", (c) => {
				out += c;
			});
			child.on("error", reject);
			child.on("exit", () => resolve(out));
		});
	}

	// The hook may have TWO things to say (proxy down, picker stale) and exactly
	// one additionalContext field to say them in. A second process.stdout.write
	// would emit two JSON objects on one stream, which is not parseable as a
	// hook result — the proxy notice would be lost.
	it("merges both notices into a single valid JSON object", async () => {
		const dir = tmp();
		// The hook resolves settings from ~/.claude/settings.json, so the fake HOME
		// must carry that directory — writing to $HOME/settings.json silently
		// yields no picker notice and the assertion below would then be measuring
		// the proxy line twice.
		fs.mkdirSync(path.join(dir, ".claude"), { recursive: true });
		fs.writeFileSync(
			path.join(dir, ".claude", "settings.json"),
			JSON.stringify({ env: { ANTHROPIC_CUSTOM_MODEL_OPTION: "glm-5.3[1m]" } }),
		);
		// Nothing on the port and no bin anywhere -> "missing-path", so BOTH lines
		// apply. 1 is always free of a cc-proxy (it is privileged and never ours).
		const out = await runHook(dir, { PROXY_PORT: "1" });
		const parsed = JSON.parse(out);
		assert.equal(parsed.hookSpecificOutput.hookEventName, "SessionStart");
		const text = parsed.hookSpecificOutput.additionalContext;
		assert.match(text, /the proxy did not start/, "the proxy notice was lost");
		assert.match(text, /200K/, "the picker notice was lost");
		// ORDER, not just presence. session-start.js's emit() docstring calls the
		// proxy line "the more urgent of the two" and puts it first; with two
		// independent match() calls that claim was unenforced — swapping the array
		// left all 49 hook tests green (measured). A proxy that will not start is
		// what breaks the session; the picker notice is advice.
		assert.ok(
			text.indexOf("the proxy did not start") < text.indexOf("200K"),
			"the picker notice preceded the proxy failure — emit()'s stated priority is inverted",
		);
	});

	// A defect in the picker path must not vanish. pickerLine()'s catch is
	// correct to swallow — an unhandled throw would take out the proxy notice
	// sharing the payload — but a BARE catch left nothing on any channel, which
	// is this repo's "a script that prints nothing may never have run" trap one
	// level down. stderr is debug-log-only for a SessionStart hook (#55), so the
	// write costs the user nothing and leaves a maintainer something to grep.
	//
	// The throw is injected by making the tree's picker-staleness.js throw on
	// import of its state, rather than by mocking: this asserts the wiring in
	// session-start.js, which is the only thing under test here.
	it("logs a picker-path defect to stderr instead of swallowing it silently", async () => {
		const dir = tmp();
		const hookPath = isolatedHook(dir);
		const broken = path.join(path.dirname(hookPath), "picker-staleness.js");
		fs.writeFileSync(
			broken,
			"export function pickerNotice() { throw new Error('injected picker defect'); }\n",
		);
		const child = spawn(process.execPath, [hookPath], {
			env: {
				...process.env,
				HOME: dir,
				USERPROFILE: dir,
				PROXY_PATH: "",
				PROXY_PORT: "1",
				PROXY_READY_TIMEOUT_MS: "300",
				PROXY_LOG: path.join(dir, "log"),
			},
			stdio: ["ignore", "pipe", "pipe"],
		});
		let stdout = "";
		let stderr = "";
		child.stdout.on("data", (c) => {
			stdout += c;
		});
		child.stderr.on("data", (c) => {
			stderr += c;
		});
		const code = await new Promise((resolve) => child.on("exit", resolve));
		assert.equal(code, 0, "a hook must never block the session, defect or not");
		assert.match(stderr, /picker-staleness check failed: injected picker defect/);
		// The proxy notice still had to survive — that is why the catch exists.
		assert.match(
			JSON.parse(stdout).hookSpecificOutput.additionalContext,
			/the proxy did not start/,
			"the picker defect took the proxy notice down with it",
		);
	});

	// Silence must stay byte-exact silence: a hook that prints "{}" on a healthy
	// session adds an empty context entry to every session forever.
	it("prints nothing at all when there is nothing to say", async () => {
		const dir = tmp();
		// The healthy path is "already-up": something already speaks the /_status
		// contract AT THE TREE'S OWN VERSION. Reporting a DIFFERENT version (or
		// none — `probeProxyVersion` resolves null for a JSON body without one)
		// makes the listener read as STALE, which sends the hook down the
		// shutdown-and-respawn branch. Matching 0.9.9 keeps this test on the
		// branch it means to test.
		const srv = http.createServer((_req, res) => {
			res.writeHead(200, { "content-type": "application/json" });
			res.end(JSON.stringify({ version: "0.9.9", providers: [] }));
		});
		await new Promise((resolve) => srv.listen(0, "127.0.0.1", resolve));
		const port = srv.address().port;
		try {
			// No settings.json and no legacy env in this HOME -> no picker notice.
			assert.equal(await runHook(dir, { PROXY_PORT: String(port) }), "");
		} finally {
			srv.closeAllConnections();
			srv.close();
		}
	});
});
